program: param_scan.py
name: graph_rx_nontensor_30db_normal_10dev_final_Nt32_offset
command:
  - ${env}
  - python3
  - ${program}
  # - ${args}
method: random #bayes
metric: # for bayes sweep
  goal: minimize
  name: validation RMSE # the exact name of the wandb.log()
  # name: validation loss # the exact name of the wandb.log()
parameters:
  # optim:
  #   values:
  #     - "ADAM"
  #     # - "SGD"
  #   distribution: categorical
  # momentum:
  #   values: [0, 0.8, 0.9, 0.95]
  activation:
    value: "LeakyReLU"
    # values:
      # - "ReLU"
      # - "ELU"
    #   - "LeakyReLU"
    # distribution: categorical
  # aggregation:
  #   values:
  #     - "mean"
  #     # - "ELU"
  #     - "lstm"
  #   distribution: categorical
  # model:
  #   values:
  #     - "mask"
  #     - "non-mask"
  # aggregation:
  #   values:
  #     - "mean"
  #     - "max"
  #   distribution: categorical
  batch_size:
    values: 
      # - 128 
      # - 256
      - 512
      - 1024
    distribution: categorical
  epochs:
    value: 200
  d_h:
    max: 2200
    min: 128
    distribution: int_uniform
  mlp_layers:
    value: 1
    # max: 2
    # min: 1
    # distribution: int_uniform
  conv_layers:
    value: 2
    # max: 3
    # min: 2
    # distribution: int_uniform
  learning_rate:
    # max: 0.005
    # min: 0.00005
    # distribution: uniform
    values: [5e-4, 1e-4, 5e-5]
      # # - 0.01
      # - 0.001 
      # - 0.0001
      # - 0.00001
    # distribution: categorical
  dropout:
    max: 0.5
    min: 0
    distribution: uniform
  weight_decay:
    values:
      # - 0.000001
      - 0.0000001
      - 0.00000001
      - 0
    distribution: categorical





  # activation:
  #   value: "LeakyReLU"
  # batch_size:
  #   values: [512,1024,2048]
  # epochs:
  #   value: 250
  # d_h:
  #   max: 2048
  #   min: 128
  #   # distribution: int_uniform
  # mlp_layers:
  #   value: [1,2]
  # conv_layers:
  #   value: 2
  # learning_rate:
  #   values: [5e-4, 1e-4, 5e-5]
  # dropout:
  #   max: 0.5
  #   min: 0
  #   distribution: uniform
  # weight_decay:
  #   values:
  #     - 0.000001
  #     - 0.0000001
  #     - 0.00000001
  #     - 0
  #   distribution: categorical

